name: Basic CI
on: [push]

jobs:
  format-check:
    env:
      RUST_BACKTRACE: 1
      API_KEY: ${{ secrets.API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Check formatting
        run: cargo fmt --all --check

  native-build-and-test:
    name: test on ${{matrix.os}}
    env:
      RUST_BACKTRACE: 1
      API_KEY: ${{ secrets.API_KEY }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  cross-build-and-test:
    name: test on ${{matrix.target}}
    env:
      RUST_BACKTRACE: 1
      API_KEY: ${{ secrets.API_KEY }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          # - os: ubuntu-latest
          #   target: x86_64-unknown-linux-musl
          # - os: windows-latest
          #   target: x86_64-pc-windows-gnu
          # - os: ubuntu-latest
          #   target: aarch64-unknown-linux-gnu
          # - os: ubuntu-latest
          #   target: aarch64-unknown-linux-musl
          # - os: ubuntu-latest
          #   target: arm-unknown-linux-gnueabi
          # - os: ubuntu-latest
          #   target: arm-unknown-linux-musleabi
          # - os: ubuntu-latest
          #   target: armv7-unknown-linux-gnueabihf
          # - os: ubuntu-latest
          #   target: armv7-unknown-linux-musleabihf
          # - os: ubuntu-latest
          #   target: powerpc64le-unknown-linux-musl
          # - os: ubuntu-latest
          #   target: riscv64gc-unknown-linux-musl
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{matrix.target}}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target ${{matrix.target}}

  docs:
    env:
      RUST_BACKTRACE: 1
      API_KEY: ${{ secrets.API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Docs
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps --document-private-items --workspace
